### ISSUE TITLE
Unable to build electron testing "e init --root=~/electron --bootstrap testing"

### ISSUE THREAD

**Issue by martinsXXX** [electron/build-tools#296] opened 2021-07-16 08:23 UTC
**I'm trying to build electron on a virtual machine (200GB hard disk, 16 GB RAM, win10). The above command fails with the error**

.....
Applying: build: conditionally import EXT headers from framework or from relative path
Hook 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 117.48 secs
subprocess2(154) __init__:python3 src/electron/script/patches-mtime-cache.py apply --cache-file src/electron/patches/mtime-cache.json;  cwd=C:\Users\martin\electron
________ running 'python3 src/electron/script/patches-mtime-cache.py apply --cache-file src/electron/patches/mtime-cache.json' in 'C:\Users\martin\electron'
subprocess2(154) __init__:python3 -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python3", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);;  cwd=C:\Users\martin\electron
________ running 'python3 -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python3", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);' in 'C:\Users\martin\electron'
npx: installed 1 in 2.182s
yarn install v1.15.2
$ node -e 'process.exit(0)'
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-standard@14.1.1" has unmet peer dependency "eslint-plugin-promise@>=4.2.1".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 72.72s.
Hook 'python3 -c 'import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python3", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);'' took 76.31 secs
subprocess2(154) __init__:vpython.bat -vpython-spec src/.vpython -vpython-tool install;  cwd=C:\Users\martin\electron
________ running 'vpython.bat -vpython-spec src/.vpython -vpython-tool install' in 'C:\Users\martin\electron'
Hook 'vpython.bat -vpython-spec src/.vpython -vpython-tool install' took 162.73 secs
subprocess2(154) __init__:vpython3 -vpython-spec src/.vpython3 -vpython-tool install;  cwd=C:\Users\martin\electron
________ running 'vpython3 -vpython-spec src/.vpython3 -vpython-tool install' in 'C:\Users\martin\electron'
Hook 'vpython3 -vpython-spec src/.vpython3 -vpython-tool install' took 195.78 secs
subprocess2(154) __init__:python3 src/build/landmines.py;  cwd=C:\Users\martin\electron
________ running 'python3 src/build/landmines.py' in 'C:\Users\martin\electron'
subprocess2(154) __init__:python3 src/third_party/depot_tools/update_depot_tools_toggle.py --disable;  cwd=C:\Users\martin\electron
________ running 'python3 src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in 'C:\Users\martin\electron'
subprocess2(154) __init__:python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools;  cwd=C:\Users\martin\electron
________ running 'python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in 'C:\Users\martin\electron'
Hook 'python3 src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' took 10.08 secs
subprocess2(154) __init__:python3 src/build/vs_toolchain.py update --force;  cwd=C:\Users\martin\electron
________ running 'python3 src/build/vs_toolchain.py update --force' in 'C:\Users\martin\electron'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: 3bda71a11e
Traceback (most recent call last):
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\martin\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\martin\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\martin\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\martin\\electron\\src\\build\\win_toolchain.json', '3bda71a11e', '--force']' returned non-zero exit status 1.
Error: Command 'python3 src/build/vs_toolchain.py update --force' returned non-zero exit status 1 in C:\Users\martin\electron
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes:
  desired_hash: 3bda71a11e
Traceback (most recent call last):
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 608, in <module>
    sys.exit(main())
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 547, in main
    DoTreeMirror(toolchain_target_dir, args.desired_hash)
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 363, in DoTreeMirror
    temp_dir, local_zip = DownloadUsingHttp(tree_sha1 + '.zip')
  File "C:\Users\martin\electron\src\third_party\depot_tools\win_toolchain\get_toolchain_if_necessary.py", line 313, in DownloadUsingHttp
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "src/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "src/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "src/build/vs_toolchain.py", line 517, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Users\martin\.electron_build_tools\third_party\depot_tools\bootstrap-2@3_8_10_chromium_19_bin\python3\bin\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\martin\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe', 'C:\\Users\\martin\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\martin\\electron\\src\\build\\win_toolchain.json', '3bda71a11e', '--force']' returned non-zero exit status 1.

ERROR Error: Command failed: python C:\Users\martin\.electron_build_tools\third_party\depot_tools\gclient.py sync --with_branch_heads --with_tags -vv -v
    at checkExecSyncError (child_process.js:643:11)
    at Object.execFileSync (child_process.js:661:15)
    at Object.depotExecFileSync [as execFileSync] (C:\Users\martin\.electron_build_tools\src\utils\depot-tools.js:118:16)
    at runGClientSync (C:\Users\martin\.electron_build_tools\src\e-sync.js:54:9)
    at Object.<anonymous> (C:\Users\martin\.electron_build_tools\src\e-sync.js:76:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
ERROR Error: Command failed: C:\Program Files\nodejs\node.exe C:\Users\martin\.electron_build_tools\src\e sync -v
    at checkExecSyncError (child_process.js:643:11)
    at Object.execFileSync (child_process.js:661:15)
    at Object.<anonymous> (C:\Users\martin\.electron_build_tools\src\e-init.js:203:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

A similar error was adressed in https://github.com/electron/build-tools/issues/293, but was closed as "Fixed". 
I'm building inside a Virtual machine win 10 64 Bit. I have followed all the instructions in https://github.com/electron/build-tools thoroughly. 
These are the steps I took, the commands were run from an administrative cmd shell. The "!!!" mark steps that made problems.
-VS CommunityEdition 2019 with debugging tools
-git
-!!!Node: tried node-v14.17.2-x64.msi, but this failed with an error message about user rights or something, so I used node-v14.17.1-x64.msi
-Set environment variable DEPOT_TOOLS_WIN_TOOLCHAIN=0
-!!!pywin32: choco install pywin32 --yes failed, reporting a problem with an URL! So I used installer from https://github.com/mhammond/pywin32/releases, version  301 for x64
-YARN; npm install --global yarn gave me "+ yarn@1.22.10 added 1 package in 0.477s"
-npm i -g @electron/build-tools gave me "+ @electron/build-tools@1.0.4   added 1 package from 1 contributor in 36.774s"
-ELECTRON e init --root=~/electron --bootstrap testing gave four "fixable errors", I said "y" to fix them automatically. Those errors were 
  WARN A fixable error has occurred
   --> git config --global core.filemode must be set to false.
    Do you want build-tools to try fix this for you? [y/n]: y
  --> git config --global core.autocrlf must be set to false.
  --> git config --global branch.autosetuprebase must be set to always.
  --> git config --global branch.autosetuprebase must be set to always.

-after more than an hour, the error above appeared. I tried "e check-for-updates" which said I'm up to date. 
-I tried to run the failing command manually from shell by 
"C:\\Users\\martin\\.electron_build_tools\\third_party\\depot_tools\\bootstrap-2@3_8_10_chromium_19_bin\\python3\\bin\\python3.exe C:\\Users\\martin\\electron\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py --output-json C:\\Users\\martin\\electron\\src\\build\\win_toolchain.json 3bda71a11e --force"
This didn't give the same error, as excpected, error was "No downloadable toolchain found. In order to use your locally installed version of Visual Studio to build Chrome please set DEPOT_TOOLS_WIN_TOOLCHAIN=0.". But this is set to 0 in my environment!

I have no idea how to solve this problem, any help would be appreciated!
=====================

The relevant environment variables in the VM are:
....
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132706369358146171
ChocolateyToolsLocation=C:\tools
DEPOT_TOOLS_WIN_TOOLCHAIN=0
HOMEPATH=\Users\martin
NUMBER_OF_PROCESSORS=1
OS=Windows_NT
Path=C:\Python39\Scripts\;C:\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\tools\python;C:\Users\martin\AppData\Local\Microsoft\WindowsApps;C:\Users\martin\AppData\Roaming\npm
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0d
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
USERNAME=martin
USERPROFILE=C:\Users\martin
....

**Comment by samuelmaddock** [comment] 2021-08-10 22:51
Could you try running `e check-for-updates` then `e sync` again to see if the problem is fixed? https://github.com/electron/build-tools/issues/293#issuecomment-878385221

**Comment by eleksir** [comment] 2021-08-16 14:04
Same error at the same string. Obviously, it tries to run python2 script with python3. Module urlparse is python2 artifact, it was merged with urllib3 in python3.

see this issue for example https://github.com/FriendCode/gittle/issues/49#issuecomment-219238005

**Comment by codebytere** [comment] 2022-05-18 08:12
This should be fixed now as we've generally migrated to python3.

**Closed by codebytere** 2022-05-18 08:12 UTC

**Comment by zcoding** [comment] 2022-08-08 08:11
shit
